version: '3.9'

services:
  sisnotificacao:
    container_name: app-sisnotificacao
    environment:
      - TZ=America/Sao_Paulo
    restart: unless-stopped
    networks:
      - web-apps
    build:
      context: .
      dockerfile: Dockerfile    
    volumes:
      - ./:/app 
      - /etc/timezone:/etc/timezone:ro 
    # -------------------------------------
    # Configurações de recursos otimizadas
    deploy:
      resources:
        limits:
          cpus: '1.0'      # Máximo 1 CPU core
          memory: 1.2G     # Máximo 1.2GB RAM
        reservations:
          cpus: '0.5'      # Reserva 50% CPU
          memory: 512M     # Reserva 512MB RAM
    # Configurações de sistema para WebSockets
    sysctls:
      - net.core.somaxconn=1024
      - net.ipv4.tcp_keepalive_time=600
      - net.ipv4.tcp_keepalive_intvl=60
      - net.ipv4.tcp_keepalive_probes=3
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 4096
        hard: 4096
    # -------------------------------------
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sisnotificacao.rule=Host(`notificacao.kingdomsys.com`)"
      - "traefik.http.routers.sisnotificacao.entrypoints=websecure"
      - "traefik.http.routers.sisnotificacao.tls=true"
      - "traefik.http.routers.sisnotificacao.tls.certresolver=letsencrypt"
      - "traefik.http.services.sisnotificacao.loadbalancer.server.port=8000"
      # Middlewares úteis (compressão e headers)
      - "traefik.http.middlewares.sisnotificacao-compress.compress=true"
      - "traefik.http.middlewares.sisnotificacao-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.sisnotificacao.middlewares=sisnotificacao-compress,sisnotificacao-headers"

      # (Opcional) Sticky se você tiver sessão em memória
      - "traefik.http.services.sisnotificacao.loadbalancer.sticky=true"
      - "traefik.http.services.sisnotificacao.loadbalancer.sticky.cookie.name=sisnotificacao"

networks:
  web-apps:
    external: true
# para inicializar: docker-compose down && docker-compose build --no-cache && docker-compose up -d --force-recreate
